-- Database: DPM

-- DROP DATABASE "DPM";

CREATE DATABASE "DPM"
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'English_India.1252'
    LC_CTYPE = 'English_India.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;
	
-- Table: public.RegisterUsers

-- DROP TABLE public."RegisterUsers";

CREATE TABLE public."RegisterUsers"
(
    "Id" text COLLATE pg_catalog."default" NOT NULL,
    "Firstname" text COLLATE pg_catalog."default",
    "Lastname" text COLLATE pg_catalog."default",
    "Company" text COLLATE pg_catalog."default",
    "UserName" text COLLATE pg_catalog."default",
    "NormalizedUserName" text COLLATE pg_catalog."default",
    "Email" text COLLATE pg_catalog."default",
    "NormalizedEmail" text COLLATE pg_catalog."default",
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text COLLATE pg_catalog."default",
    "SecurityStamp" text COLLATE pg_catalog."default",
    "ConcurrencyStamp" text COLLATE pg_catalog."default",
    "PhoneNumber" text COLLATE pg_catalog."default",
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    "ImageUrl" text COLLATE pg_catalog."default",
    "UserType" integer,
    CONSTRAINT "PK_RegisterUsers" PRIMARY KEY ("Id")
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."RegisterUsers"
    OWNER to dpm;


-- Table: public.addrulemodel

-- DROP TABLE public.addrulemodel;

CREATE TABLE public.addrulemodel
(
    "AddRuleId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Columns" text COLLATE pg_catalog."default",
    "Alarm" real NOT NULL,
    "Trigger" real NOT NULL,
    "Condition" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_addrulemodel" PRIMARY KEY ("AddRuleId")
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.addrulemodel
    OWNER to dpm;


-- Table: public.centrifugalpump

-- DROP TABLE public.centrifugalpump;

CREATE TABLE public.centrifugalpump
(
    "CentrifugalPumpId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "UserId" text COLLATE pg_catalog."default",
    "TagNumber" text COLLATE pg_catalog."default",
    "InsertedDate" date,
    "PI025" numeric,
    "PI022" numeric,
    "PI023" numeric,
    "PI027" numeric,
    "PE203" numeric,
    "TI061" numeric,
    "TI062" numeric,
    "TI263" numeric,
    "Date" date,
    CONSTRAINT centrifugalpump_pkey PRIMARY KEY ("CentrifugalPumpId")
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.centrifugalpump
    OWNER to dpm;

	
-- Table: public.centrifugalpumpfailuremodes

-- DROP TABLE public.centrifugalpumpfailuremodes;

CREATE TABLE public.centrifugalpumpfailuremodes
(
    "CPPFMId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "CFPPrescriptiveId" integer NOT NULL,
    "FunctionMode" text COLLATE pg_catalog."default",
    "LocalEffect" text COLLATE pg_catalog."default",
    "SystemEffect" text COLLATE pg_catalog."default",
    "Consequence" text COLLATE pg_catalog."default",
    "DownTimeFactor" integer,
    "ScrapeFactor" integer,
    "SafetyFactor" integer,
    "ProtectionFactor" integer,
    "FrequencyFactor" integer,
    "CriticalityFactor" integer,
    "MaintainenancePractice" text COLLATE pg_catalog."default",
    "FrequencyMaintainenance" text COLLATE pg_catalog."default",
    "ConditionMonitoring" text COLLATE pg_catalog."default",
    "Rating" text COLLATE pg_catalog."default",
    "AttachmentDBPath" text COLLATE pg_catalog."default",
    "AttachmentFullPath" text COLLATE pg_catalog."default",
    "Remark" text COLLATE pg_catalog."default",
    "Pattern" text COLLATE pg_catalog."default",
    "FCACondition" text COLLATE pg_catalog."default",
    "FCAInterval" integer,
    "FCAFFI" text COLLATE pg_catalog."default",
    "FCAComment" text COLLATE pg_catalog."default",
    "FCAAlpha" numeric,
    "FCABeta" numeric,
    "FCASafeLife" numeric,
    "FCAUsefulLife" numeric,
    "MSSMaintenanceInterval" text COLLATE pg_catalog."default",
    "MSSStartergy" text COLLATE pg_catalog."default",
    "MSSMaintenanceTask" text COLLATE pg_catalog."default",
    "FCAUpdateIntervals" text COLLATE pg_catalog."default",
    "FCAUpdateConditions" text COLLATE pg_catalog."default",
    "MSSAvailability" numeric,
    "MSSIntervalSelectionCriteria" text COLLATE pg_catalog."default",
    CONSTRAINT centrifugalpumpfailuremodes_pkey PRIMARY KEY ("CPPFMId")
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.centrifugalpumpfailuremodes
    OWNER to dpm;
	
	
-- Table: public.centrifugalpumpweekdata

-- DROP TABLE public.centrifugalpumpweekdata;

CREATE TABLE public.centrifugalpumpweekdata
(
    "CPWId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "TagNumber" text COLLATE pg_catalog."default",
    "UserId" text COLLATE pg_catalog."default",
    "Date" date,
    "InsertedDate" date,
    "OneH" numeric,
    "OneV" numeric,
    "TwoH" numeric,
    "TwoV" numeric,
    "TwoA" numeric,
    "ThreeH" numeric,
    "ThreeV" numeric,
    "ThreeA" numeric,
    "FourH" numeric,
    "FourV" numeric,
    "OneT" numeric,
    "TwoT" numeric,
    "ThreeT" numeric,
    "FourT" numeric,
    "AMP" numeric,
    CONSTRAINT centrifugalpumpweekdata_pkey PRIMARY KEY ("CPWId")
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.centrifugalpumpweekdata
    OWNER to dpm;
	

-- Table: public.compressuredetails

-- DROP TABLE public.compressuredetails;

CREATE TABLE public.compressuredetails
(
    "BatchId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "TenantId" integer NOT NULL,
    "PS1" numeric NOT NULL,
    "PD1" numeric NOT NULL,
    "PS2" numeric NOT NULL,
    "PD2" numeric NOT NULL,
    "TS1" numeric NOT NULL,
    "TD1" numeric NOT NULL,
    "TS2" numeric NOT NULL,
    "TD2" numeric NOT NULL,
    "InsertedDate" timestamp without time zone NOT NULL,
    "ProcessingStage" text COLLATE pg_catalog."default",
    "UserId" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_compressuredetails" PRIMARY KEY ("BatchId")
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.compressuredetails
    OWNER to dpm;


-- Table: public.compressurewithclassification

-- DROP TABLE public.compressurewithclassification;

CREATE TABLE public.compressurewithclassification
(
    "CompClassID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "BatchId" integer NOT NULL,
    "TenantId" integer NOT NULL,
    "ClassificationId" integer NOT NULL,
    "PS1" numeric NOT NULL,
    "PD1" numeric NOT NULL,
    "PS2" numeric NOT NULL,
    "PD2" numeric NOT NULL,
    "TS1" numeric NOT NULL,
    "TD1" numeric NOT NULL,
    "TS2" numeric NOT NULL,
    "TD2" numeric NOT NULL,
    "InsertedDate" timestamp without time zone NOT NULL,
    "Classification" text COLLATE pg_catalog."default",
    "UserId" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_compressurewithclassification" PRIMARY KEY ("CompClassID")
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.compressurewithclassification
    OWNER to dpm;

-- Table: public.contactus

-- DROP TABLE public.contactus;

CREATE TABLE public.contactus
(
    "ContactUsId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Comment" text COLLATE pg_catalog."default",
    "Email" text COLLATE pg_catalog."default",
    "Subject" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_contactus" PRIMARY KEY ("ContactUsId")
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.contactus
    OWNER to dpm;
	
	
-- Table: public.dpmprescriptive

-- DROP TABLE public.dpmprescriptive;

CREATE TABLE public.dpmprescriptive
(
    "CFPPrescriptiveId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "UserId" text COLLATE pg_catalog."default",
    "MachineType" text COLLATE pg_catalog."default",
    "EquipmentType" text COLLATE pg_catalog."default",
    "TagNumber" text COLLATE pg_catalog."default",
    "FunctionFluidType" text COLLATE pg_catalog."default",
    "FunctionRatedHead" text COLLATE pg_catalog."default",
    "FunctionPeriodType" text COLLATE pg_catalog."default",
    "FunctionFailure" text COLLATE pg_catalog."default",
    "Date" date,
    "FailureModeWithLSETree" text COLLATE pg_catalog."default",
    "FMWithConsequenceTree" text COLLATE pg_catalog."default",
    "ComponentCriticalityFactor" integer,
    "ComponentRating" text COLLATE pg_catalog."default",
    "CMaintainenancePractice" text COLLATE pg_catalog."default",
    "CFrequencyMaintainenance" text COLLATE pg_catalog."default",
    "CConditionMonitoring" text COLLATE pg_catalog."default",
    "CAttachmentDBPath" text COLLATE pg_catalog."default",
    "CAttachmentFullPath" text COLLATE pg_catalog."default",
    "CRemarks" text COLLATE pg_catalog."default",
    "FCAAdded" text COLLATE pg_catalog."default",
    "MSSAdded" text COLLATE pg_catalog."default",
    CONSTRAINT dpmprescriptive_pkey PRIMARY KEY ("CFPPrescriptiveId")
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.dpmprescriptive
    OWNER to dpm;


-- Table: public.prescriptive_lookupmaster

-- DROP TABLE public.prescriptive_lookupmaster;

CREATE TABLE public.prescriptive_lookupmaster
(
    "PrescriptiveLookupMasterId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Description" text COLLATE pg_catalog."default",
    "MachineType" text COLLATE pg_catalog."default",
    "EquipmentType" text COLLATE pg_catalog."default",
    "Function" text COLLATE pg_catalog."default",
    "Date" date,
    CONSTRAINT prescriptive_lookupmaster_pkey PRIMARY KEY ("PrescriptiveLookupMasterId")
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.prescriptive_lookupmaster
    OWNER to dpm;

-- Table: public.rcatable

-- DROP TABLE public.rcatable;

CREATE TABLE public.rcatable
(
    "RCAID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "TagNumber" text COLLATE pg_catalog."default",
    "RCATree" text COLLATE pg_catalog."default",
    "RCACode" text COLLATE pg_catalog."default",
    "RCACompletionPercentage" numeric,
    "UserId" text COLLATE pg_catalog."default",
    CONSTRAINT rcatable_pkey PRIMARY KEY ("RCAID")
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.rcatable
    OWNER to dpm;


-- Table: public.recyclecentrifugalpumpfailuremodes

-- DROP TABLE public.recyclecentrifugalpumpfailuremodes;

CREATE TABLE public.recyclecentrifugalpumpfailuremodes
(
    "RCPFMId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "RCPPMId" integer NOT NULL,
    "UserId" text COLLATE pg_catalog."default",
    "CPPFMId" integer NOT NULL,
    "CFPPrescriptiveId" integer NOT NULL,
    "FunctionMode" text COLLATE pg_catalog."default",
    "LocalEffect" text COLLATE pg_catalog."default",
    "SystemEffect" text COLLATE pg_catalog."default",
    "Consequence" text COLLATE pg_catalog."default",
    "DownTimeFactor" integer,
    "ScrapeFactor" integer,
    "SafetyFactor" integer,
    "ProtectionFactor" integer,
    "FrequencyFactor" integer,
    "CriticalityFactor" integer,
    "MaintainenancePractice" text COLLATE pg_catalog."default",
    "FrequencyMaintainenance" text COLLATE pg_catalog."default",
    "ConditionMonitoring" text COLLATE pg_catalog."default",
    "Rating" text COLLATE pg_catalog."default",
    "AttachmentDBPath" text COLLATE pg_catalog."default",
    "AttachmentFullPath" text COLLATE pg_catalog."default",
    "Remark" text COLLATE pg_catalog."default",
    "IsDeleted" integer,
    "DeletedFMTree" text COLLATE pg_catalog."default",
    "Pattern" text COLLATE pg_catalog."default",
    "FCACondition" text COLLATE pg_catalog."default",
    "FCAInterval" integer,
    "FCAFFI" text COLLATE pg_catalog."default",
    "FCAComment" text COLLATE pg_catalog."default",
    "FCAAlpha" numeric,
    "FCABeta" numeric,
    "FCASafeLife" numeric,
    "FCAUsefulLife" numeric,
    "FCAUpdateIntervals" text COLLATE pg_catalog."default",
    "FCAUpdateConditions" text COLLATE pg_catalog."default",
    "MSSMaintenanceInterval" text COLLATE pg_catalog."default",
    "MSSAvailability" numeric,
    "MSSStartergy" text COLLATE pg_catalog."default",
    "MSSMaintenanceTask" text COLLATE pg_catalog."default",
    "MSSIntervalSelectionCriteria" text COLLATE pg_catalog."default",
    CONSTRAINT recyclecentrifugalpumpfailuremodes_pkey PRIMARY KEY ("RCPFMId")
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.recyclecentrifugalpumpfailuremodes
    OWNER to dpm;


-- Table: public.recycledpmprescriptive

-- DROP TABLE public.recycledpmprescriptive;

CREATE TABLE public.recycledpmprescriptive
(
    "RCPPMId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "CFPPrescriptiveId" integer NOT NULL,
    "UserId" text COLLATE pg_catalog."default",
    "MachineType" text COLLATE pg_catalog."default",
    "EquipmentType" text COLLATE pg_catalog."default",
    "TagNumber" text COLLATE pg_catalog."default",
    "FunctionFluidType" text COLLATE pg_catalog."default",
    "FunctionRatedHead" text COLLATE pg_catalog."default",
    "FunctionPeriodType" text COLLATE pg_catalog."default",
    "FunctionFailure" text COLLATE pg_catalog."default",
    "Date" date,
    "FailureModeWithLSETree" text COLLATE pg_catalog."default",
    "FMWithConsequenceTree" text COLLATE pg_catalog."default",
    "ComponentCriticalityFactor" integer,
    "ComponentRating" text COLLATE pg_catalog."default",
    "CMaintainenancePractice" text COLLATE pg_catalog."default",
    "CFrequencyMaintainenance" text COLLATE pg_catalog."default",
    "CConditionMonitoring" text COLLATE pg_catalog."default",
    "CAttachmentDBPath" text COLLATE pg_catalog."default",
    "CAttachmentFullPath" text COLLATE pg_catalog."default",
    "CRemarks" text COLLATE pg_catalog."default",
    "CIsDeleted" integer,
    "FCAAdded" text COLLATE pg_catalog."default",
    "MSSAdded" text COLLATE pg_catalog."default",
    CONSTRAINT recycledpmprescriptive_pkey PRIMARY KEY ("RCPPMId")
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.recycledpmprescriptive
    OWNER to dpm;

-- Table: public.screwcompressorfutureprediction

-- DROP TABLE public.screwcompressorfutureprediction;

CREATE TABLE public.screwcompressorfutureprediction
(
    "SCFPId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "UserId" text COLLATE pg_catalog."default" NOT NULL,
    "TenantId" integer,
    "BatchId" integer,
    "PS1" numeric,
    "PD1" numeric,
    "PS2" numeric,
    "PD2" numeric,
    "TS1" numeric,
    "TD1" numeric,
    "TS2" numeric,
    "TD2" numeric,
    "PredictedDate" date,
    "Prediction" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_screwcompressorfutureprediction" PRIMARY KEY ("SCFPId")
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.screwcompressorfutureprediction
    OWNER to dpm;


-- Table: public.screwcompressorpredictiontable

-- DROP TABLE public.screwcompressorpredictiontable;

CREATE TABLE public.screwcompressorpredictiontable
(
    "PredictionId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "BatchId" integer NOT NULL,
    "TenantId" integer NOT NULL,
    "PS1" numeric NOT NULL,
    "PD1" numeric NOT NULL,
    "PS2" numeric NOT NULL,
    "PD2" numeric NOT NULL,
    "TS1" numeric NOT NULL,
    "TD1" numeric NOT NULL,
    "TS2" numeric NOT NULL,
    "TD2" numeric NOT NULL,
    "InsertedDate" timestamp without time zone NOT NULL,
    "Prediction" text COLLATE pg_catalog."default",
    "UserId" text COLLATE pg_catalog."default",
    "FuturePrediction" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_screwcompressorpredictiontable" PRIMARY KEY ("PredictionId")
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.screwcompressorpredictiontable
    OWNER to dpm;	










