// <auto-generated />
using System;
using DPM_Testing.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DPM_Testing.Migrations
{
    [DbContext(typeof(DPMDal))]
    [Migration("20201213152133_LoginRegistartion")]
    partial class LoginRegistartion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("DPM_Testing.Models.AddRuleModel", b =>
                {
                    b.Property<int>("AddRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<float>("Alarm")
                        .HasColumnType("real");

                    b.Property<string>("Columns")
                        .HasColumnType("text");

                    b.Property<string>("Condition")
                        .HasColumnType("text");

                    b.Property<float>("Trigger")
                        .HasColumnType("real");

                    b.HasKey("AddRuleId");

                    b.ToTable("addrulemodel");
                });

            modelBuilder.Entity("DPM_Testing.Models.ClassificationMaster", b =>
                {
                    b.Property<int>("ClassificationMasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("ClassificationId")
                        .HasColumnType("integer");

                    b.Property<string>("Classifications")
                        .HasColumnType("text");

                    b.HasKey("ClassificationMasterId");

                    b.ToTable("classificationMaster");
                });

            modelBuilder.Entity("DPM_Testing.Models.ContactUs", b =>
                {
                    b.Property<int>("ContactUsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.HasKey("ContactUsId");

                    b.ToTable("contactus");
                });

            modelBuilder.Entity("DPM_Testing.Models.ProfileModel", b =>
                {
                    b.Property<int>("ProfileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Company")
                        .HasColumnType("text");

                    b.Property<string>("Contact")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FocalPersonName")
                        .HasColumnType("text");

                    b.HasKey("ProfileID");

                    b.ToTable("profile");
                });

            modelBuilder.Entity("DPM_Testing.Models.RegisterUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RegisterUsers");
                });

            modelBuilder.Entity("DPM_Testing.Models.RegistrationModel", b =>
                {
                    b.Property<int>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("RegistrationId");

                    b.ToTable("registeruser");
                });

            modelBuilder.Entity("DPM_Testing.Models.compressuredetails", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("PD1")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PD2")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PS1")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PS2")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TD1")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TD2")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TS1")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TS2")
                        .HasColumnType("numeric");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("BatchId");

                    b.ToTable("compressuredetails");
                });

            modelBuilder.Entity("DPM_Testing.Models.compressurewithclassification", b =>
                {
                    b.Property<int>("CompClassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("BatchId")
                        .HasColumnType("integer");

                    b.Property<string>("Classification")
                        .HasColumnType("text");

                    b.Property<int>("ClassificationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("PD1")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PD2")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PS1")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PS2")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TD1")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TD2")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TS1")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TS2")
                        .HasColumnType("numeric");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("CompClassID");

                    b.ToTable("compressurewithclassification");
                });
#pragma warning restore 612, 618
        }
    }
}
